version: '3.8'

networks:
  web:
    name: web-network

services:
  apache-php:
    build: ./apache-php
    container_name: apache-php-cont
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:80"
    networks:
      - web

  postgresql:
    build: ./postgresql
    container_name: postgresql-cont
    env_file:
     - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql/postgresql-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - web